Basic project Setup
GDGVIT/keats-ios pull request #1
Opened 2021-02-08 08:57 UTC by swamitagupta

# Pull Request Type
Please check the type of change your PR introduces:
- [x] Refactoring (no functional changes, no api changes)

# Purpose
- Updating README.md with list of features and setting up a basic iOS project

# Approach
- Marks the starting of a new project

# Does this PR introduce any new bug?
- [x] No

2021-02-08 15:59 UTC, BRO3886 requested changes
Don't remove <directions to install> and <directions to execute>. Those are headings.

Can be something like this
< directions to install > 
```bash
git clone github.com/GDGVIT/keats-ios
```

< directions to execute >
-  Import the project in XCode
- Change the bundle id and run the project

2021-02-08 16:54 UTC, swamitagupta commented
> Don't remove `<directions to install>` and `<directions to execute>`. Those are headings.
> 
> Can be something like this
> < directions to install >
> 
> ```shell
> git clone github.com/GDGVIT/keats-ios
> ```
> 
> < directions to execute >
> 
> * Import the project in XCode
> * Change the bundle id and run the project

Sure, made the required changes.

2021-02-09 04:11 UTC, BRO3886 reviewed
LGTM. Fixes #1.

2021-02-09 04:11 UTC, BRO3886 approved these changes

2021-02-09 04:11 UTC, merged